# Import libraries

In [1]:
import pandas as pd
import numpy  as np

# Read datasets

In [ ]:
# Main data for analisis
main_dataset            = pd.read_csv(r"data\raw\application_train.csv")
bureau                  = pd.read_csv(r"data\raw\bureau.csv")
ccbalance               = pd.read_csv(r"data\raw\credit_card_balance.csv")
installments_payments   = pd.read_csv(r"data\raw\installments_payments.csv")
pos_cash_balance        = pd.read_csv(r"data\raw\POS_CASH_balance.csv")
sample_submission       = pd.read_csv(r"data\raw\sample_submission.csv")
prev_application        = pd.read_csv(r"data\raw\previous_application.csv")
bureau_balance          = pd.read_csv(r"data\raw\bureau_balance.csv")


# Auxiliar datasets
# app_test                = pd.read_csv(r"data\raw\HC_application_test.csv")
home_desc               = pd.read_csv(r"data\raw\HomeCredit_columns_description.csv",
                                        encoding = 'latin1')

In [3]:
home_desc

# Target variable 
# (1 - client with payment difficulties: 
# he/she had late payment more than X days 
# on at least one of the first Y installments 
# of the loan in our sample,
#  0 - all other cases)

,Unnamed: 0,Table,Row,Description,Special
0,1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN
1,2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN
2,5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN
3,6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN
4,7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN
...,...,...,...,...,...
214,217,installments_payments.csv,NUM_INSTALMENT_NUMBER,On which installment we observe payment,NaN
215,218,installments_payments.csv,DAYS_INSTALMENT,When the installment of previous credit was su...,time only relative to the application
216,219,installments_payments.csv,DAYS_ENTRY_PAYMENT,When was the installments of previous credit p...,time only relative to the application
217,220,installments_payments.csv,AMT_INSTALMENT,What was the prescribed installment amount of ...,NaN
218,221,installments_payments.csv,AMT_PAYMENT,What the client actually paid on previous cred...,NaN

In [4]:
ccbalance.sort_values(by = ['SK_ID_CURR','MONTHS_BALANCE'], ascending= [True, False])

# Amortization table for each client
# summary will be required for next analysis, 
# need insights for each client

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
584804,1489396,100006,-1,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
520387,1489396,100006,-2,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1347528,1489396,100006,-3,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1399895,1489396,100006,-4,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
655566,1489396,100006,-5,0.000,270000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2985617,1794451,456250,-8,177219.000,180000,0.0,0.0,0.0,0.0,9465.705,...,176958.900,176958.900,0.0,0,0.0,0.0,3.0,Active,0,0
3734047,1794451,456250,-9,180536.760,180000,0.0,0.0,0.0,0.0,9653.985,...,179866.260,179866.260,0.0,0,0.0,0.0,2.0,Active,0,0
1684283,1794451,456250,-10,186577.605,180000,0.0,0.0,0.0,0.0,9892.485,...,185907.105,185907.105,0.0,0,0.0,0.0,1.0,Active,0,0
3611324,1794451,456250,-11,200208.915,180000,9000.0,9000.0,0.0,0.0,0.000,...,196581.915,196581.915,1.0,1,0.0,0.0,0.0,Active,0,0
3000394,1794451,456250,-12,181993.500,180000,171000.0,171000.0,0.0,0.0,0.000,...,171000.000,171000.000,7.0,7,0.0,0.0,0.0,Active,0,0

In [5]:
print("Main dataset \n",)
display(main_dataset)

print("Credit historic data \n",)
display(bureau)

print("Time series info about credit historic dataset \n",)
display(bureau_balance)

print("Credit card information \n",)
display(ccbalance)

print("Previous iformation about previous loans \n",)
display(installments_payments)

print("Information about account balances, habits, savings and financial stability \n",)
display(pos_cash_balance)

print("Information about previous loan applications \n",)
display(prev_application)

Main dataset

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

Credit historic data

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,0,11250.00,11250.0,0.0,0.0,Microloan,-19,NaN
1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.5,0,38130.84,0.0,0.0,0.0,Consumer credit,-2493,NaN
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,15570.00,NaN,NaN,0.0,Consumer credit,-967,NaN
1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,36000.00,0.0,0.0,0.0,Consumer credit,-1508,NaN
1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,22500.00,0.0,NaN,0.0,Microloan,-387,NaN

Time series info about credit historic dataset

          SK_ID_BUREAU  MONTHS_BALANCE STATUS
0              5715448               0      C
1              5715448              -1      C
2              5715448              -2      C
3              5715448              -3      C
4              5715448              -4      C
...                ...             ...    ...
27299920       5041336             -47      X
27299921       5041336             -48      X
27299922       5041336             -49      X
27299923       5041336             -50      X
27299924       5041336             -51      X

[27299925 rows x 3 columns]

Credit card information

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840307,1036507,328243,-9,0.000,45000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840308,1714892,347207,-9,0.000,45000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,23.0,Active,0,0
3840309,1302323,215757,-9,275784.975,585000,270000.0,270000.0,0.0,0.0,2250.000,...,273093.975,273093.975,2.0,2,0.0,0.0,18.0,Active,0,0
3840310,1624872,430337,-10,0.000,450000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840311,2411345,236760,-10,0.000,157500,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,21.0,Completed,0,0

Previous iformation about previous loans

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.0,6,-1180.0,-1187.0,6948.360,6948.360
1,1330831,151639,0.0,34,-2156.0,-2156.0,1716.525,1716.525
2,2085231,193053,2.0,1,-63.0,-63.0,25425.000,25425.000
3,2452527,199697,1.0,3,-2418.0,-2426.0,24350.130,24350.130
4,2714724,167756,1.0,2,-1383.0,-1366.0,2165.040,2160.585
...,...,...,...,...,...,...,...,...
13605396,2186857,428057,0.0,66,-1624.0,NaN,67.500,NaN
13605397,1310347,414406,0.0,47,-1539.0,NaN,67.500,NaN
13605398,1308766,402199,0.0,43,-7.0,NaN,43737.435,NaN
13605399,1062206,409297,0.0,43,-1986.0,NaN,67.500,NaN
13605400,2448869,434321,1.0,19,-27.0,NaN,11504.250,NaN

Information about account balances, habits, savings and financial stability

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0
...,...,...,...,...,...,...,...,...
10001353,2448283,226558,-20,6.0,0.0,Active,843,0
10001354,1717234,141565,-19,12.0,0.0,Active,602,0
10001355,1283126,315695,-21,10.0,0.0,Active,609,0
10001356,1082516,450255,-22,12.0,0.0,Active,614,0
10001357,1259607,174278,-52,16.0,0.0,Completed,0,0

Information about previous loan applications

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670209,2300464,352015,Consumer loans,14704.290,267295.5,311400.0,0.0,267295.5,WEDNESDAY,12,...,Furniture,30.0,low_normal,POS industry with interest,365243.0,-508.0,362.0,-358.0,-351.0,0.0
1670210,2357031,334635,Consumer loans,6622.020,87750.0,64291.5,29250.0,87750.0,TUESDAY,15,...,Furniture,12.0,middle,POS industry with interest,365243.0,-1604.0,-1274.0,-1304.0,-1297.0,0.0
1670211,2659632,249544,Consumer loans,11520.855,105237.0,102523.5,10525.5,105237.0,MONDAY,12,...,Consumer electronics,10.0,low_normal,POS household with interest,365243.0,-1457.0,-1187.0,-1187.0,-1181.0,0.0
1670212,2785582,400317,Cash loans,18821.520,180000.0,191880.0,NaN,180000.0,WEDNESDAY,9,...,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-1155.0,-825.0,-825.0,-817.0,1.0
1670213,2418762,261212,Cash loans,16431.300,360000.0,360000.0,NaN,360000.0,SUNDAY,10,...,XNA,48.0,middle,Cash X-Sell: middle,365243.0,-1163.0,247.0,-443.0,-423.0,0.0

## Bureau

In [6]:
bureau

# Need to make a singuler porfile per each SK_ID_CURR. 
# categorical variables convert to binaries, and numerical to mean, max, min 
# depending each context

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,0,11250.00,11250.0,0.0,0.0,Microloan,-19,NaN
1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.5,0,38130.84,0.0,0.0,0.0,Consumer credit,-2493,NaN
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,15570.00,NaN,NaN,0.0,Consumer credit,-967,NaN
1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,36000.00,0.0,0.0,0.0,Consumer credit,-1508,NaN
1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,22500.00,0.0,NaN,0.0,Microloan,-387,NaN

In [7]:
bureau_fe = bureau.copy()

#  Variables derivadas / ratios financieros

# Ratio deuda / crédito total:
# mide qué proporción del crédito otorgado sigue pendiente de pago
# Valores altos pueden indicar mayor carga financiera o exposición al riesgo
bureau_fe['DEBT_RATIO'] = np.where(
    bureau_fe['AMT_CREDIT_SUM'] > 0,
    bureau_fe['AMT_CREDIT_SUM_DEBT'] / bureau_fe['AMT_CREDIT_SUM'],
    np.nan
)

# Ratio mora / crédito total:
# mide qué proporción del crédito total está vencida
# Ayuda a capturar severidad de incumplimiento, no solo si existe mora
bureau_fe['OVERDUE_RATIO'] = np.where(
    bureau_fe['AMT_CREDIT_SUM'] > 0,
    bureau_fe['AMT_CREDIT_SUM_OVERDUE'] / bureau_fe['AMT_CREDIT_SUM'],
    np.nan
)

# Uso del límite de crédito:
# mide qué tanto del límite disponible está siendo utilizado como deuda
# Es útil especialmente en créditos tipo tarjeta o líneas de crédito
bureau_fe['LIMIT_USAGE'] = np.where(
    bureau_fe['AMT_CREDIT_SUM_LIMIT'] > 0,
    bureau_fe['AMT_CREDIT_SUM_DEBT'] / bureau_fe['AMT_CREDIT_SUM_LIMIT'],
    np.nan
)

# Ratio anualidad / crédito total:
# aproxima qué tan pesada es la cuota anual respecto al monto del crédito
# Valores altos pueden reflejar mayor presión de pago para el cliente
bureau_fe['ANNUITY_CREDIT_RATIO'] = np.where(
    bureau_fe['AMT_CREDIT_SUM'] > 0,
    bureau_fe['AMT_ANNUITY'] / bureau_fe['AMT_CREDIT_SUM'],
    np.nan
)

# Indicador de mora:
# identifica si el crédito tiene algún monto vencido
# Luego puede agregarse por cliente para obtener cantidad o proporción de créditos con mora
bureau_fe['HAS_OVERDUE'] = (
    bureau_fe['AMT_CREDIT_SUM_OVERDUE'] > 0
).astype(int)

# Indicador de deuda vigente:
# identifica si el cliente todavía tiene deuda pendiente en ese crédito
# Sirve para medir exposición activa al riesgo.
bureau_fe['HAS_DEBT'] = (
    bureau_fe['AMT_CREDIT_SUM_DEBT'] > 0
).astype(int)

# Indicador de crédito activo:
# marca si el crédito sigue abierto
# Permite calcular cuántos o qué proporción de créditos activos tiene cada cliente
bureau_fe['CREDIT_IS_ACTIVE'] = (
    bureau_fe['CREDIT_ACTIVE'] == 'Active'
).astype(int)

# Indicador de crédito cerrado:
# marca si el crédito ya fue cerrado.
# Una alta proporción de créditos cerrados puede reflejar historial crediticio completado.
bureau_fe['CREDIT_IS_CLOSED'] = (
    bureau_fe['CREDIT_ACTIVE'] == 'Closed'
).astype(int)


# Creamos dummies de variables categóricas
bureau_fe = pd.get_dummies(
    bureau_fe,
    columns=['CREDIT_ACTIVE', 'CREDIT_TYPE'],
    dtype=int
)


# Hacemos la agregación por cliente
bureau_summary = (
    bureau_fe
    .groupby('SK_ID_CURR')
    .agg({

        # Identificadores / volumen
        'SK_ID_BUREAU': ['count'],

        # Tiempo
        'DAYS_CREDIT': ['min', 'max', 'mean'],
        'CREDIT_DAY_OVERDUE': ['max', 'mean', 'sum'],
        'DAYS_CREDIT_ENDDATE': ['min', 'max', 'mean'],
        'DAYS_ENDDATE_FACT': ['min', 'max', 'mean'],
        'DAYS_CREDIT_UPDATE': ['min', 'max', 'mean'],

        # Montos de crédito
        'AMT_CREDIT_SUM': ['min', 'max', 'mean', 'sum'],
        'AMT_CREDIT_SUM_DEBT': ['min', 'max', 'mean', 'sum'],
        'AMT_CREDIT_SUM_LIMIT': ['min', 'max', 'mean', 'sum'],
        'AMT_CREDIT_SUM_OVERDUE': ['max', 'mean', 'sum'],
        'AMT_CREDIT_MAX_OVERDUE': ['max', 'mean'],

        # Anualidad
        'AMT_ANNUITY': ['max', 'mean', 'sum'],

        # Prolongaciones
        'CNT_CREDIT_PROLONG': ['max', 'mean', 'sum'],

        # Ratios
        'DEBT_RATIO': ['max', 'mean'],
        'OVERDUE_RATIO': ['max', 'mean'],
        'LIMIT_USAGE': ['max', 'mean'],
        'ANNUITY_CREDIT_RATIO': ['max', 'mean'],

        # Indicadores
        'HAS_OVERDUE': ['mean', 'sum'],
        'HAS_DEBT': ['mean', 'sum'],
        'CREDIT_IS_ACTIVE': ['mean', 'sum'],
        'CREDIT_IS_CLOSED': ['mean', 'sum'],

        # Dummies CREDIT_ACTIVE
        'CREDIT_ACTIVE_Active': ['mean'],
        'CREDIT_ACTIVE_Bad debt': ['mean'],
        'CREDIT_ACTIVE_Closed': ['mean'],
        'CREDIT_ACTIVE_Sold': ['mean'],

        # Dummies CREDIT_TYPE
        'CREDIT_TYPE_Another type of loan': ['mean'],
        'CREDIT_TYPE_Car loan': ['mean'],
        'CREDIT_TYPE_Cash loan (non-earmarked)': ['mean'],
        'CREDIT_TYPE_Consumer credit': ['mean'],
        'CREDIT_TYPE_Credit card': ['mean'],
        'CREDIT_TYPE_Interbank credit': ['mean'],
        'CREDIT_TYPE_Loan for business development': ['mean'],
        'CREDIT_TYPE_Loan for purchase of shares (margin lending)': ['mean'],
        'CREDIT_TYPE_Loan for the purchase of equipment': ['mean'],
        'CREDIT_TYPE_Loan for working capital replenishment': ['mean'],
        'CREDIT_TYPE_Microloan': ['mean'],
        'CREDIT_TYPE_Mobile operator loan': ['mean'],
        'CREDIT_TYPE_Mortgage': ['mean'],
        'CREDIT_TYPE_Real estate loan': ['mean'],
        'CREDIT_TYPE_Unknown type of loan': ['mean']
    })
)

# Modificamos nombres de columnas
bureau_summary.columns = [
    f'BUREAU_{col[0]}_{col[1]}'
    for col in bureau_summary.columns
]

bureau_summary = bureau_summary.reset_index()

#limpiamos infinitos y nulos derivados
bureau_summary = bureau_summary.replace([np.inf, -np.inf], np.nan)

In [8]:
bureau_summary.shape

(305811, 75)

In [9]:
bureau_summary.head(10)

,SK_ID_CURR,BUREAU_SK_ID_BUREAU_count,BUREAU_DAYS_CREDIT_min,BUREAU_DAYS_CREDIT_max,BUREAU_DAYS_CREDIT_mean,BUREAU_CREDIT_DAY_OVERDUE_max,BUREAU_CREDIT_DAY_OVERDUE_mean,BUREAU_CREDIT_DAY_OVERDUE_sum,BUREAU_DAYS_CREDIT_ENDDATE_min,BUREAU_DAYS_CREDIT_ENDDATE_max,...,BUREAU_CREDIT_TYPE_Interbank credit_mean,BUREAU_CREDIT_TYPE_Loan for business development_mean,BUREAU_CREDIT_TYPE_Loan for purchase of shares (margin lending)_mean,BUREAU_CREDIT_TYPE_Loan for the purchase of equipment_mean,BUREAU_CREDIT_TYPE_Loan for working capital replenishment_mean,BUREAU_CREDIT_TYPE_Microloan_mean,BUREAU_CREDIT_TYPE_Mobile operator loan_mean,BUREAU_CREDIT_TYPE_Mortgage_mean,BUREAU_CREDIT_TYPE_Real estate loan_mean,BUREAU_CREDIT_TYPE_Unknown type of loan_mean
0,100001,7,-1572,-49,-735.000000,0,0.0,0,-1329.0,1778.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,100002,8,-1437,-103,-874.000000,0,0.0,0,-1072.0,780.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,100003,4,-2586,-606,-1400.750000,0,0.0,0,-2434.0,1216.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,100004,2,-1326,-408,-867.000000,0,0.0,0,-595.0,-382.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,100005,3,-373,-62,-190.666667,0,0.0,0,-128.0,1324.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,100007,1,-1149,-1149,-1149.000000,0,0.0,0,-783.0,-783.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,100008,3,-1097,-78,-757.333333,0,0.0,0,-853.0,471.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,100009,18,-2882,-239,-1271.500000,0,0.0,0,-2152.0,1402.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,100010,2,-2741,-1138,-1939.500000,0,0.0,0,-928.0,689.0,...,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,100011,4,-2508,-1309,-1773.000000,0,0.0,0,-2173.0,-860.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Installments_payments

In [10]:
# Copia del dataframe
installments_fe = installments_payments.copy()

# Diferencia entre pago realizado y pago esperado:
# mide cuánto pagó de más o de menos respecto a la cuota programada
# Valores negativos indican subpago; positivos indican sobrepago
installments_fe['PAYMENT_DIFF'] = (
    installments_fe['AMT_PAYMENT']
    - installments_fe['AMT_INSTALMENT']
)

# Ratio de pago:
# mide qué proporción de la cuota esperada fue realmente pagada
# Valores:
#   = 1  -> pago exacto
#   < 1  -> pago incompleto
#   > 1  -> sobrepago
installments_fe['PAYMENT_RATIO'] = np.where(
    installments_fe['AMT_INSTALMENT'] > 0,
    installments_fe['AMT_PAYMENT']
    / installments_fe['AMT_INSTALMENT'],
    np.nan
)

# Days Past Due (DPD):
# mide cuántos días después de la fecha límite se realizó el pago
# Es una de las variables más importantes en riesgo crediticio
# Valores altos suelen asociarse con mayor probabilidad de default
installments_fe['DPD'] = (
    installments_fe['DAYS_ENTRY_PAYMENT']
    - installments_fe['DAYS_INSTALMENT']
)

# Days Before Due (DBD):
# mide cuántos días antes de la fecha límite se realizó el pago
# Captura comportamiento preventivo o disciplina financiera
installments_fe['DBD'] = (
    installments_fe['DAYS_INSTALMENT']
    - installments_fe['DAYS_ENTRY_PAYMENT']
)

# Eliminamos negativos en DPD:
# si el valor es negativo significa que pagó antes
# por lo tanto no existe retraso
installments_fe['DPD'] = (
    installments_fe['DPD']
    .apply(lambda x: max(x, 0))
)

# Eliminamos negativos en DBD:
# si el valor es negativo significa que pagó tarde
# por lo tanto no existe adelanto
installments_fe['DBD'] = (
    installments_fe['DBD']
    .apply(lambda x: max(x, 0))
)

# Indicador de pago tardío:
# identifica si el cliente pagó después de la fecha límite
# Luego puede agregarse para obtener proporción de pagos tardíos
installments_fe['LATE_PAYMENT'] = (
    installments_fe['DPD'] > 0
).astype(int)

# Indicador de pago adelantado:
# identifica si el cliente pagó antes de la fecha límite
# Puede reflejar mejor comportamiento financiero
installments_fe['EARLY_PAYMENT'] = (
    installments_fe['DBD'] > 0
).astype(int)

# Indicador de subpago:
# identifica si el cliente pagó menos de lo esperado
# Útil para detectar problemas de liquidez o incumplimiento parcial
installments_fe['UNDERPAID'] = (
    installments_fe['AMT_PAYMENT']
    < installments_fe['AMT_INSTALMENT']
).astype(int)

# Indicador de sobrepago:
# identifica pagos mayores al monto esperado
# Puede indicar liquidaciones anticipadas o pagos extraordinarios
installments_fe['OVERPAID'] = (
    installments_fe['AMT_PAYMENT']
    > installments_fe['AMT_INSTALMENT']
).astype(int)

# Indicador de pago exacto:
# identifica si el cliente pagó exactamente el monto esperado
# Ayuda a medir estabilidad y cumplimiento regular
installments_fe['EXACT_PAYMENT'] = (
    installments_fe['AMT_PAYMENT']
    == installments_fe['AMT_INSTALMENT']
).astype(int)


# Aggregacion por cliente

installments_summary = (
    installments_fe
    .groupby('SK_ID_CURR')
    .agg({

        # Número de créditos previos
        'SK_ID_PREV': ['nunique'],

        # Número de versiones
        'NUM_INSTALMENT_VERSION': ['nunique','max'],

        # Número de cuotas
        'NUM_INSTALMENT_NUMBER': ['max','mean','count'],

        # Fechas programadas
        'DAYS_INSTALMENT': [ 'min','max','mean'],

        # Fechas reales de pago
        'DAYS_ENTRY_PAYMENT': [ 'min','max','mean'],

        # Monto esperado
        'AMT_INSTALMENT': ['min','max','mean', 'sum'],

        # Monto pagado
        'AMT_PAYMENT': ['min','max','mean','sum'],

        # Diferencia de pago
        'PAYMENT_DIFF': ['min','max','mean','sum'],

        # Ratio de pago
        'PAYMENT_RATIO': ['min','max','mean'],

        # Retrasos
        'DPD': ['max','mean','sum'],

        # Adelantos
        'DBD': ['max','mean','sum'],

        # Indicadores
        'LATE_PAYMENT': ['mean','sum'],
        'EARLY_PAYMENT': ['mean','sum'],
        'UNDERPAID': ['mean','sum'],
        'OVERPAID': ['mean','sum'],
        'EXACT_PAYMENT': ['mean','sum']

    })
)


# Aplanar nombres de columnas

installments_summary.columns = [
    f'INSTAL_{col[0]}_{col[1]}'
    for col in installments_summary.columns
]

installments_summary = installments_summary.reset_index()

# Limpieza de infinitos

installments_summary = installments_summary.replace(
    [np.inf, -np.inf],
    np.nan
)

In [11]:
installments_summary.shape

(339587, 44)

In [12]:
installments_summary.head(10)

,SK_ID_CURR,INSTAL_SK_ID_PREV_nunique,INSTAL_NUM_INSTALMENT_VERSION_nunique,INSTAL_NUM_INSTALMENT_VERSION_max,INSTAL_NUM_INSTALMENT_NUMBER_max,INSTAL_NUM_INSTALMENT_NUMBER_mean,INSTAL_NUM_INSTALMENT_NUMBER_count,INSTAL_DAYS_INSTALMENT_min,INSTAL_DAYS_INSTALMENT_max,INSTAL_DAYS_INSTALMENT_mean,...,INSTAL_LATE_PAYMENT_mean,INSTAL_LATE_PAYMENT_sum,INSTAL_EARLY_PAYMENT_mean,INSTAL_EARLY_PAYMENT_sum,INSTAL_UNDERPAID_mean,INSTAL_UNDERPAID_sum,INSTAL_OVERPAID_mean,INSTAL_OVERPAID_sum,INSTAL_EXACT_PAYMENT_mean,INSTAL_EXACT_PAYMENT_sum
0,100001,2,2,2.0,4,2.714286,7,-2916.0,-1619.0,-2187.714286,...,0.142857,1,0.571429,4,0.000000,0,0.0,0,1.000000,7
1,100002,1,2,2.0,19,10.000000,19,-565.0,-25.0,-295.000000,...,0.000000,0,1.000000,19,0.000000,0,0.0,0,1.000000,19
2,100003,3,2,2.0,12,5.080000,25,-2310.0,-536.0,-1378.160000,...,0.000000,0,1.000000,25,0.000000,0,0.0,0,1.000000,25
3,100004,1,2,2.0,3,2.000000,3,-784.0,-724.0,-754.000000,...,0.000000,0,1.000000,3,0.000000,0,0.0,0,1.000000,3
4,100005,1,2,2.0,9,5.000000,9,-706.0,-466.0,-586.000000,...,0.111111,1,0.888889,8,0.000000,0,0.0,0,1.000000,9
5,100006,3,2,2.0,10,4.437500,16,-545.0,-11.0,-252.250000,...,0.000000,0,1.000000,16,0.000000,0,0.0,0,1.000000,16
6,100007,5,2,2.0,17,7.045455,66,-2326.0,-14.0,-1028.606061,...,0.242424,16,0.621212,41,0.090909,6,0.0,0,0.909091,60
7,100008,4,2,2.0,10,5.057143,35,-2491.0,-69.0,-1263.914286,...,0.028571,1,0.971429,34,0.057143,2,0.0,0,0.942857,33
8,100009,8,1,1.0,12,4.549020,51,-2908.0,-43.0,-855.823529,...,0.019608,1,0.980392,50,0.000000,0,0.0,0,1.000000,51
9,100010,1,1,1.0,10,5.500000,10,-1039.0,-769.0,-904.000000,...,0.000000,0,1.000000,10,0.000000,0,0.0,0,1.000000,10

## pos_cash_balance

In [13]:
pos_cash_balance.info()

<class 'pandas.DataFrame'>
RangeIndex: 10001358 entries, 0 to 10001357
Data columns (total 8 columns):
 #   Column                 Dtype
---  ------                 -----
 0   SK_ID_PREV             int64
 1   SK_ID_CURR             int64
 2   MONTHS_BALANCE         int64
 3   CNT_INSTALMENT         float64
 4   CNT_INSTALMENT_FUTURE  float64
 5   NAME_CONTRACT_STATUS   str
 6   SK_DPD                 int64
 7   SK_DPD_DEF             int64
dtypes: float64(2), int64(5), str(1)
memory usage: 610.4 MB

In [14]:
pos_cash_fe = pos_cash_balance.copy()

# Variables derivadas

# Ratio de cuotas restantes:
# mide qué proporción del crédito sigue pendiente
# Valores altos indican créditos aún poco avanzados
pos_cash_fe['INSTALMENT_FUTURE_RATIO'] = np.where(
    pos_cash_fe['CNT_INSTALMENT'] > 0,
    pos_cash_fe['CNT_INSTALMENT_FUTURE']
    / pos_cash_fe['CNT_INSTALMENT'],
    np.nan
)

# Cuotas ya pagadas:
# aproxima cuántas cuotas han sido completadas
pos_cash_fe['INSTALMENTS_PAID'] = (
    pos_cash_fe['CNT_INSTALMENT']
    - pos_cash_fe['CNT_INSTALMENT_FUTURE']
)

# Indicador de retraso:
# identifica si existe atraso en pagos POS/Cash
pos_cash_fe['HAS_DPD'] = (
    pos_cash_fe['SK_DPD'] > 0
).astype(int)

# Indicador de atraso severo:
# SK_DPD_DEF representa atraso con tolerancia vencida
# Suele capturar mora más grave.
pos_cash_fe['HAS_DPD_DEF'] = (
    pos_cash_fe['SK_DPD_DEF'] > 0
).astype(int)

# Indicador de contrato activo:
# identifica créditos POS/Cash aún vigentes
pos_cash_fe['CONTRACT_ACTIVE'] = (
    pos_cash_fe['NAME_CONTRACT_STATUS']
    == 'Active'
).astype(int)

# Indicador de contrato completado:
# identifica créditos finalizados correctamente
pos_cash_fe['CONTRACT_COMPLETED'] = (
    pos_cash_fe['NAME_CONTRACT_STATUS']
    == 'Completed'
).astype(int)

# Indicador de contrato firmado:
# puede representar créditos recientemente originados
pos_cash_fe['CONTRACT_SIGNED'] = (
    pos_cash_fe['NAME_CONTRACT_STATUS']
    == 'Signed'
).astype(int)

# Indicador de demanda/deuda problemática:
# contratos asociados a problemas legales o incumplimiento
pos_cash_fe['CONTRACT_DEMAND'] = (
    pos_cash_fe['NAME_CONTRACT_STATUS']
    == 'Demand'
).astype(int)

# Indicador de créditos aprobados:
# útil para medir historial de aprobación
pos_cash_fe['CONTRACT_APPROVED'] = (
    pos_cash_fe['NAME_CONTRACT_STATUS']
    == 'Approved'
).astype(int)

# One Hot Encoding
pos_cash_fe = pd.get_dummies(
    pos_cash_fe,
    columns=['NAME_CONTRACT_STATUS'],
    dtype=int
)

# Aggregation por cliente
pos_cash_summary = (
    pos_cash_fe
    .groupby('SK_ID_CURR')
    .agg({

        # Cantidad de créditos POS/CASH
        'SK_ID_PREV': ['nunique'],

        # Historial temporal
        'MONTHS_BALANCE': ['min','max','mean'],

        # Número total de cuotas
        'CNT_INSTALMENT': ['min','max','mean','sum'],

        # Cuotas futuras
        'CNT_INSTALMENT_FUTURE': ['min','max','mean','sum'],

        # Ratio cuotas restantes
        'INSTALMENT_FUTURE_RATIO': ['min','max','mean'],

        # Cuotas pagadas
        'INSTALMENTS_PAID': ['min','max','mean','sum'],

        # Days past due
        'SK_DPD': ['max','mean','sum'],

        # Days past due default
        'SK_DPD_DEF': ['max','mean','sum'],

        # Indicadores
        'HAS_DPD': ['mean','sum'],
        'HAS_DPD_DEF': ['mean','sum'],
        'CONTRACT_ACTIVE': ['mean','sum'],
        'CONTRACT_COMPLETED': ['mean','sum'],
        'CONTRACT_SIGNED': ['mean','sum'],
        'CONTRACT_DEMAND': ['mean','sum'],
        'CONTRACT_APPROVED': ['mean','sum']

    })
)

# Aplanar nombres de columnas
pos_cash_summary.columns = [
    f'POS_{col[0]}_{col[1]}'
    for col in pos_cash_summary.columns
]

pos_cash_summary = pos_cash_summary.reset_index()

# Limpieza
pos_cash_summary = pos_cash_summary.replace(
    [np.inf, -np.inf],
    np.nan
)

In [15]:
pos_cash_summary.shape

(337252, 40)

In [16]:
pos_cash_summary.head(10)

,SK_ID_CURR,POS_SK_ID_PREV_nunique,POS_MONTHS_BALANCE_min,POS_MONTHS_BALANCE_max,POS_MONTHS_BALANCE_mean,POS_CNT_INSTALMENT_min,POS_CNT_INSTALMENT_max,POS_CNT_INSTALMENT_mean,POS_CNT_INSTALMENT_sum,POS_CNT_INSTALMENT_FUTURE_min,...,POS_CONTRACT_ACTIVE_mean,POS_CONTRACT_ACTIVE_sum,POS_CONTRACT_COMPLETED_mean,POS_CONTRACT_COMPLETED_sum,POS_CONTRACT_SIGNED_mean,POS_CONTRACT_SIGNED_sum,POS_CONTRACT_DEMAND_mean,POS_CONTRACT_DEMAND_sum,POS_CONTRACT_APPROVED_mean,POS_CONTRACT_APPROVED_sum
0,100001,2,-96,-53,-72.555556,4.0,4.0,4.000000,36.0,0.0,...,0.777778,7,0.222222,2,0.000000,0,0.0,0,0.0,0
1,100002,1,-19,-1,-10.000000,24.0,24.0,24.000000,456.0,6.0,...,1.000000,19,0.000000,0,0.000000,0,0.0,0,0.0,0
2,100003,3,-77,-18,-43.785714,6.0,12.0,10.107143,283.0,0.0,...,0.928571,26,0.071429,2,0.000000,0,0.0,0,0.0,0
3,100004,1,-27,-24,-25.500000,3.0,4.0,3.750000,15.0,0.0,...,0.750000,3,0.250000,1,0.000000,0,0.0,0,0.0,0
4,100005,1,-25,-15,-20.000000,9.0,12.0,11.700000,117.0,0.0,...,0.818182,9,0.090909,1,0.090909,1,0.0,0,0.0,0
5,100006,3,-20,-1,-9.619048,1.0,48.0,12.000000,240.0,0.0,...,0.857143,18,0.095238,2,0.000000,0,0.0,0,0.0,0
6,100007,5,-77,-1,-33.636364,10.0,24.0,15.333333,1012.0,0.0,...,0.939394,62,0.045455,3,0.015152,1,0.0,0,0.0,0
7,100008,4,-84,-2,-43.662651,6.0,30.0,11.518072,956.0,0.0,...,0.939759,78,0.048193,4,0.012048,1,0.0,0,0.0,0
8,100009,8,-96,-1,-33.062500,5.0,12.0,7.875000,504.0,0.0,...,0.890625,57,0.109375,7,0.000000,0,0.0,0,0.0,0
9,100010,1,-35,-25,-30.000000,10.0,10.0,10.000000,110.0,0.0,...,0.909091,10,0.090909,1,0.000000,0,0.0,0,0.0,0

## prev_application

In [17]:
prev_application

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670209,2300464,352015,Consumer loans,14704.290,267295.5,311400.0,0.0,267295.5,WEDNESDAY,12,...,Furniture,30.0,low_normal,POS industry with interest,365243.0,-508.0,362.0,-358.0,-351.0,0.0
1670210,2357031,334635,Consumer loans,6622.020,87750.0,64291.5,29250.0,87750.0,TUESDAY,15,...,Furniture,12.0,middle,POS industry with interest,365243.0,-1604.0,-1274.0,-1304.0,-1297.0,0.0
1670211,2659632,249544,Consumer loans,11520.855,105237.0,102523.5,10525.5,105237.0,MONDAY,12,...,Consumer electronics,10.0,low_normal,POS household with interest,365243.0,-1457.0,-1187.0,-1187.0,-1181.0,0.0
1670212,2785582,400317,Cash loans,18821.520,180000.0,191880.0,NaN,180000.0,WEDNESDAY,9,...,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-1155.0,-825.0,-825.0,-817.0,1.0
1670213,2418762,261212,Cash loans,16431.300,360000.0,360000.0,NaN,360000.0,SUNDAY,10,...,XNA,48.0,middle,Cash X-Sell: middle,365243.0,-1163.0,247.0,-443.0,-423.0,0.0

In [18]:
prev_application.info()

<class 'pandas.DataFrame'>
RangeIndex: 1670214 entries, 0 to 1670213
Data columns (total 37 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   SK_ID_PREV                   1670214 non-null  int64
 1   SK_ID_CURR                   1670214 non-null  int64
 2   NAME_CONTRACT_TYPE           1670214 non-null  str
 3   AMT_ANNUITY                  1297979 non-null  float64
 4   AMT_APPLICATION              1670214 non-null  float64
 5   AMT_CREDIT                   1670213 non-null  float64
 6   AMT_DOWN_PAYMENT             774370 non-null   float64
 7   AMT_GOODS_PRICE              1284699 non-null  float64
 8   WEEKDAY_APPR_PROCESS_START   1670214 non-null  str
 9   HOUR_APPR_PROCESS_START      1670214 non-null  int64
 10  FLAG_LAST_APPL_PER_CONTRACT  1670214 non-null  str
 11  NFLAG_LAST_APPL_IN_DAY       1670214 non-null  int64
 12  RATE_DOWN_PAYMENT            774370 non-null   float64
 13  RATE_INTEREST_PRIMARY        5951 non-null     float64
 14  RATE_INTEREST_PRIVILEGED     5951 non-null     float64
 15  NAME_CASH_LOAN_PURPOSE       1670214 non-null  str
 16  NAME_CONTRACT_STATUS         1670214 non-null  str
 17  DAYS_DECISION                1670214 non-null  int64
 18  NAME_PAYMENT_TYPE            1670214 non-null  str
 19  CODE_REJECT_REASON           1670214 non-null  str
 20  NAME_TYPE_SUITE              849809 non-null   str
 21  NAME_CLIENT_TYPE             1670214 non-null  str
 22  NAME_GOODS_CATEGORY          1670214 non-null  str
 23  NAME_PORTFOLIO               1670214 non-null  str
 24  NAME_PRODUCT_TYPE            1670214 non-null  str
 25  CHANNEL_TYPE                 1670214 non-null  str
 26  SELLERPLACE_AREA             1670214 non-null  int64
 27  NAME_SELLER_INDUSTRY         1670214 non-null  str
 28  CNT_PAYMENT                  1297984 non-null  float64
 29  NAME_YIELD_GROUP             1670214 non-null  str
 30  PRODUCT_COMBINATION          1669868 non-null  str
 31  DAYS_FIRST_DRAWING           997149 non-null   float64
 32  DAYS_FIRST_DUE               997149 non-null   float64
 33  DAYS_LAST_DUE_1ST_VERSION    997149 non-null   float64
 34  DAYS_LAST_DUE                997149 non-null   float64
 35  DAYS_TERMINATION             997149 non-null   float64
 36  NFLAG_INSURED_ON_APPROVAL    997149 non-null   float64
dtypes: float64(15), int64(6), str(16)
memory usage: 471.5 MB

# EDA

In [19]:
main_dataset

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

#

In [22]:
bureau_summary

,SK_ID_CURR,BUREAU_SK_ID_BUREAU_count,BUREAU_DAYS_CREDIT_min,BUREAU_DAYS_CREDIT_max,BUREAU_DAYS_CREDIT_mean,BUREAU_CREDIT_DAY_OVERDUE_max,BUREAU_CREDIT_DAY_OVERDUE_mean,BUREAU_CREDIT_DAY_OVERDUE_sum,BUREAU_DAYS_CREDIT_ENDDATE_min,BUREAU_DAYS_CREDIT_ENDDATE_max,...,BUREAU_CREDIT_TYPE_Interbank credit_mean,BUREAU_CREDIT_TYPE_Loan for business development_mean,BUREAU_CREDIT_TYPE_Loan for purchase of shares (margin lending)_mean,BUREAU_CREDIT_TYPE_Loan for the purchase of equipment_mean,BUREAU_CREDIT_TYPE_Loan for working capital replenishment_mean,BUREAU_CREDIT_TYPE_Microloan_mean,BUREAU_CREDIT_TYPE_Mobile operator loan_mean,BUREAU_CREDIT_TYPE_Mortgage_mean,BUREAU_CREDIT_TYPE_Real estate loan_mean,BUREAU_CREDIT_TYPE_Unknown type of loan_mean
0,100001,7,-1572,-49,-735.000000,0,0.0,0,-1329.0,1778.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,100002,8,-1437,-103,-874.000000,0,0.0,0,-1072.0,780.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,100003,4,-2586,-606,-1400.750000,0,0.0,0,-2434.0,1216.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,100004,2,-1326,-408,-867.000000,0,0.0,0,-595.0,-382.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,100005,3,-373,-62,-190.666667,0,0.0,0,-128.0,1324.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305806,456249,13,-2713,-483,-1667.076923,0,0.0,0,-2499.0,1363.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
305807,456250,3,-1002,-760,-862.000000,0,0.0,0,-272.0,2340.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
305808,456253,4,-919,-713,-867.500000,0,0.0,0,-189.0,1113.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
305809,456254,1,-1104,-1104,-1104.000000,0,0.0,0,-859.0,-859.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
305810,456255,11,-2337,-363,-1089.454545,0,0.0,0,-1243.0,27320.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
installments_summary

,SK_ID_CURR,INSTAL_SK_ID_PREV_nunique,INSTAL_NUM_INSTALMENT_VERSION_nunique,INSTAL_NUM_INSTALMENT_VERSION_max,INSTAL_NUM_INSTALMENT_NUMBER_max,INSTAL_NUM_INSTALMENT_NUMBER_mean,INSTAL_NUM_INSTALMENT_NUMBER_count,INSTAL_DAYS_INSTALMENT_min,INSTAL_DAYS_INSTALMENT_max,INSTAL_DAYS_INSTALMENT_mean,...,INSTAL_LATE_PAYMENT_mean,INSTAL_LATE_PAYMENT_sum,INSTAL_EARLY_PAYMENT_mean,INSTAL_EARLY_PAYMENT_sum,INSTAL_UNDERPAID_mean,INSTAL_UNDERPAID_sum,INSTAL_OVERPAID_mean,INSTAL_OVERPAID_sum,INSTAL_EXACT_PAYMENT_mean,INSTAL_EXACT_PAYMENT_sum
0,100001,2,2,2.0,4,2.714286,7,-2916.0,-1619.0,-2187.714286,...,0.142857,1,0.571429,4,0.000000,0,0.000000,0,1.000000,7
1,100002,1,2,2.0,19,10.000000,19,-565.0,-25.0,-295.000000,...,0.000000,0,1.000000,19,0.000000,0,0.000000,0,1.000000,19
2,100003,3,2,2.0,12,5.080000,25,-2310.0,-536.0,-1378.160000,...,0.000000,0,1.000000,25,0.000000,0,0.000000,0,1.000000,25
3,100004,1,2,2.0,3,2.000000,3,-784.0,-724.0,-754.000000,...,0.000000,0,1.000000,3,0.000000,0,0.000000,0,1.000000,3
4,100005,1,2,2.0,9,5.000000,9,-706.0,-466.0,-586.000000,...,0.111111,1,0.888889,8,0.000000,0,0.000000,0,1.000000,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339582,456251,1,2,2.0,7,4.000000,7,-210.0,-30.0,-120.000000,...,0.000000,0,1.000000,7,0.000000,0,0.000000,0,1.000000,7
339583,456252,1,1,1.0,6,3.500000,6,-2466.0,-2316.0,-2391.000000,...,0.166667,1,0.666667,4,0.000000,0,0.000000,0,1.000000,6
339584,456253,3,1,1.0,12,4.785714,14,-2915.0,-1716.0,-2372.928571,...,0.071429,1,0.571429,8,0.142857,2,0.000000,0,0.857143,12
339585,456254,2,1,1.0,10,5.263158,19,-291.0,-7.0,-142.263158,...,0.000000,0,1.000000,19,0.000000,0,0.000000,0,1.000000,19
339586,456255,6,4,4.0,24,8.851351,74,-960.0,-66.0,-463.945946,...,0.189189,14,0.783784,58,0.243243,18,0.027027,2,0.729730,54

In [23]:
pos_cash_summary

,SK_ID_CURR,POS_SK_ID_PREV_nunique,POS_MONTHS_BALANCE_min,POS_MONTHS_BALANCE_max,POS_MONTHS_BALANCE_mean,POS_CNT_INSTALMENT_min,POS_CNT_INSTALMENT_max,POS_CNT_INSTALMENT_mean,POS_CNT_INSTALMENT_sum,POS_CNT_INSTALMENT_FUTURE_min,...,POS_CONTRACT_ACTIVE_mean,POS_CONTRACT_ACTIVE_sum,POS_CONTRACT_COMPLETED_mean,POS_CONTRACT_COMPLETED_sum,POS_CONTRACT_SIGNED_mean,POS_CONTRACT_SIGNED_sum,POS_CONTRACT_DEMAND_mean,POS_CONTRACT_DEMAND_sum,POS_CONTRACT_APPROVED_mean,POS_CONTRACT_APPROVED_sum
0,100001,2,-96,-53,-72.555556,4.0,4.0,4.000000,36.0,0.0,...,0.777778,7,0.222222,2,0.000000,0,0.0,0,0.0,0
1,100002,1,-19,-1,-10.000000,24.0,24.0,24.000000,456.0,6.0,...,1.000000,19,0.000000,0,0.000000,0,0.0,0,0.0,0
2,100003,3,-77,-18,-43.785714,6.0,12.0,10.107143,283.0,0.0,...,0.928571,26,0.071429,2,0.000000,0,0.0,0,0.0,0
3,100004,1,-27,-24,-25.500000,3.0,4.0,3.750000,15.0,0.0,...,0.750000,3,0.250000,1,0.000000,0,0.0,0,0.0,0
4,100005,1,-25,-15,-20.000000,9.0,12.0,11.700000,117.0,0.0,...,0.818182,9,0.090909,1,0.090909,1,0.0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337247,456251,1,-9,-1,-5.000000,7.0,8.0,7.875000,63.0,0.0,...,0.777778,7,0.111111,1,0.111111,1,0.0,0,0.0,0
337248,456252,1,-82,-76,-79.000000,6.0,6.0,6.000000,42.0,0.0,...,0.857143,6,0.142857,1,0.000000,0,0.0,0,0.0,0
337249,456253,3,-96,-57,-79.235294,4.0,12.0,6.705882,114.0,0.0,...,0.882353,15,0.117647,2,0.000000,0,0.0,0,0.0,0
337250,456254,2,-11,-1,-5.550000,14.0,16.0,14.900000,298.0,4.0,...,1.000000,20,0.000000,0,0.000000,0,0.0,0,0.0,0
337251,456255,6,-33,-2,-16.408451,3.0,36.0,22.788732,1618.0,0.0,...,0.915493,65,0.084507,6,0.000000,0,0.0,0,0.0,0

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670209,2300464,352015,Consumer loans,14704.290,267295.5,311400.0,0.0,267295.5,WEDNESDAY,12,...,Furniture,30.0,low_normal,POS industry with interest,365243.0,-508.0,362.0,-358.0,-351.0,0.0
1670210,2357031,334635,Consumer loans,6622.020,87750.0,64291.5,29250.0,87750.0,TUESDAY,15,...,Furniture,12.0,middle,POS industry with interest,365243.0,-1604.0,-1274.0,-1304.0,-1297.0,0.0
1670211,2659632,249544,Consumer loans,11520.855,105237.0,102523.5,10525.5,105237.0,MONDAY,12,...,Consumer electronics,10.0,low_normal,POS household with interest,365243.0,-1457.0,-1187.0,-1187.0,-1181.0,0.0
1670212,2785582,400317,Cash loans,18821.520,180000.0,191880.0,NaN,180000.0,WEDNESDAY,9,...,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-1155.0,-825.0,-825.0,-817.0,1.0
1670213,2418762,261212,Cash loans,16431.300,360000.0,360000.0,NaN,360000.0,SUNDAY,10,...,XNA,48.0,middle,Cash X-Sell: middle,365243.0,-1163.0,247.0,-443.0,-423.0,0.0

In [20]:
%who_ls

['bureau',
 'bureau_balance',
 'bureau_fe',
 'bureau_summary',
 'ccbalance',
 'home_desc',
 'installments_fe',
 'installments_payments',
 'installments_summary',
 'main_dataset',
 'np',
 'pd',
 'pos_cash_balance',
 'pos_cash_fe',
 'pos_cash_summary',
 'prev_application',
 'sample_submission']

In [25]:
sample_submission

       SK_ID_CURR  TARGET
0          100001     0.5
1          100005     0.5
2          100013     0.5
3          100028     0.5
4          100038     0.5
...           ...     ...
48739      456221     0.5
48740      456222     0.5
48741      456223     0.5
48742      456224     0.5
48743      456250     0.5

[48744 rows x 2 columns]

# Processing data

## Missing values

## Outliers (detection, handling)

## Feature encoding

## Feature transformation

## Feature selection

## Train test split